### PR TITLE
Upgrade emotion and docz dependencies, to be compatible with docz 0.13.7

### LINKED ISSUE #9: Cannot read property 'mq' of undefined
I'm unable to apply this theme because of the error mentioned in the title.

I guess you need to port over this bugfix from the default theme:

https://github.com/pedronauck/docz/commit/5596446 as mentioned at https://github.com/pedronauck/docz/issues/452#issuecomment-439402682

### PR DESCRIPTION
**Pull request by smeijer**
As explained in #9, I was unable to start `docz`, when using this theme. 

Fixed the issue by upgrading some dependencies. Mostly migrated `react-emotion` to `@emotion/core` and `@emotion/styled`. Also upgraded `docz` to `0.13.7` and `webpack` due to some [webpack issues](https://github.com/pedronauck/docz/issues/596#issuecomment-456288810).

The good news, I can now start `docz` with this theme (a local clone that is):

```js
export default {
  theme: 'docz-theme-hydrate/dist',
}
```

**The bad news**
I do have some rendering issues. But I'm unable to say if that's this branch specific, or that they are already present in the current version. 

@jpeters5392, it would be awesome if you could take a look.

---

Fixes #9

### CODE REVIEW

**Comment by smeijer** [comment]
@jpeters5392, is this theme being used on some public documentation site? So I can compare?

**Comment by smeijer** [comment]
Ok, I've killed a few things.

Turns out, `import { css } from '@emotion/core'` has different behaviour than `import { css } from 'emotion'`.

https://github.com/emotion-js/emotion/issues/1092

**Comment by jpeters5392** [comment]
@smeijer I pulled it down and took a look.  Your PR upgrades it to 0.14.0 of docz which actually doesn't exist.  As far as I can tell, the only 0.14.x releases are explicitly tagged as alpha so they wouldn't resolve for me.  However, if I downgrade it back to 0.13.7 then it works.  Unfortunately at this point the documentation site that was the driver for this library is still under development, but when it is released I think the plan is to make it publicly available.

I see 2 main rendering issues when I look around at your PR.  

1. It looks like the anchor links in the sidebars are getting passed an object for a className instead of a string, and that might be an artifact of the emotion upgrade.
2. The styles for `h1` tags is a little messed up because of some negative margins that we had in there to make it match our client mockups.  @kevindavi5 we will probably need to figure out how to remove the negative margins from here since they look pretty weird standalone.

**Comment by jpeters5392** [comment]
It looks like you and I found the same issue with css at the same time :)

**Comment by smeijer** [comment]
Looks like that :) I've fixed it a couple of seconds ago. Looking much better now!

I don't understand why you're thinking I'm using docz `0.14` though. I'm clearly having `docz: ^0.13.7` in my `package.json`.

**Comment by jpeters5392** [comment]
Oh, sorry about that.  I was in a multi-project workspace and I was looking at my version of your repro package.json when I was fiddling with versions.

**Comment by jpeters5392** [comment]
Once you push up that CSS fix then I'll take another look at the PR.  I'm glad to hear that it is working a lot better now.

**Comment by jpeters5392** [comment]
Ah, you have pushed.  I was looking at master.  I'll take another look.

**Comment by smeijer** [comment]
I did before my comment :)

Basically, import `css` from `emotion` when it's being passed to a `className`. Import `css` from `@emotion/core` when it's being used by `Global`.

It's all looking fine. But my sidebar is not looking the same as the screenshots in the readme.

**Comment by jpeters5392** [comment]
It looks like we need to update the README.  We originally started with indented sub-links in the sidebar as well as having the search in the sidebar, but about a month ago our client asked us to flatten the lists and move the search into the main content.  It looks like when we did that we forgot to grab screenshots and update the README.  Although @kevindavi5 and I were having some conversations about how we would like to be able to make it so that the search location is configurable.

**Comment by smeijer** [comment]
If you're adding some config options; I would love to have the collapsing of menus configurable as well.

The reason I was trying this theme out, is because the screenshots made it look like the menus didn't collapse. But indented instead.

**Review by jpeters5392 — APPROVED** [review]
I think this looks good to me.

**Comment by smeijer** [comment]
Awesome!

So, it is also expected that I have the project name 2 times in the sidebar? Or is that a config thing?

image

**Comment by jpeters5392** [comment]
The menus collapse but the sub-headings on the current page used to indent which is what you see in the screenshots.  It doesn't look like those screenshots had any menus in them.  I'll file some issues to update the README/screenshots as well as making the menu collapsing configurable and adding some config options for the project name.  

I'll go ahead and merge this over for now and cut a 2.0.0-alpha1 release..

**Pull request merged**
